# /home/dazhi/webapp/fly.toml
# See https://fly.io/docs/reference/configuration/ for all available options

app = "dazhi-webapp" # Replace with a unique name for your app on Fly.io
primary_region = "iad" # Choose a region close to your users: https://fly.io/docs/reference/regions/

[build]
  # This tells Fly to build the app using the Dockerfile in the same directory
  builder = "dockerfile"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"] # Corresponds to the default process from the Dockerfile CMD